apiVersion: apps/v1
kind: Deployment 
metadata:
  name: meudeployment2
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web2
          image: guilherme53/conversao-peso:v10
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web2
spec:
  selector:
    app: web
  ports:
    - port: 80
      protocol: TCP
      name: http
      nodePort: 30001
  type: LoadBalancer 
